# Generated by Django 5.0.7 on 2024-07-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'requester'), (2, 'donor'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
