# Generated by Django 5.0.7 on 2024-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'requester'), (1, 'admin'), (2, 'donor')], default=1, max_length=50),
        ),
    ]
