# Generated by Django 5.0.7 on 2024-07-18 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0003_bloodgroup_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (3, 'requester'), (2, 'donor')], default=1, max_length=50),
        ),
        migrations.CreateModel(
            name='DonorReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('mobilenumber', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('regdate_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbdmsapp.bloodgroup')),
            ],
        ),
    ]
