# Generated by Django 5.0.7 on 2024-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0006_contact_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorreg',
            name='status',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(3, 'requester'), (1, 'admin'), (2, 'donor')], default=1, max_length=50),
        ),
    ]
