# Generated by Django 5.1.1 on 2024-10-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbdmsapp', '0020_alter_bloodrequest_mobno_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'donor'), (3, 'requester')], default=1, max_length=50),
        ),
    ]
